<?php
// module/ImageSpeedTest/view/imagespeedtest/imagespeedtest/index.phtml:

$title = 'My imagespeedtests';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('imagespeedtest', array('action'=>'add'));?>">Add new imagespeedtest</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($imagespeedtests as $imagespeedtest) : ?>
<tr>
    <td><?php echo $this->escapeHtml($imagespeedtest->title);?></td>
    <td><?php echo $this->escapeHtml($imagespeedtest->artist);?></td>
    <td>
        <a href="<?php echo $this->url('imagespeedtest',
            array('action'=>'edit', 'id' => $imagespeedtest->id));?>">Edit</a>
        <a href="<?php echo $this->url('imagespeedtest',
            array('action'=>'delete', 'id' => $imagespeedtest->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>